# Generated by Django 4.2.13 on 2026-06-01 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='invoice_number',
            field=models.CharField(blank=True, editable=False, max_length=50, unique=True, verbose_name='Número da Nota Fiscal'),
        ),
    ]
